### ISSUE TITLE
`validate_subaccount` always returns true regardless of size

### ISSUE THREAD

**Issue by Web3NL** [NatLabs/icrc1#11]
in Utils.mo

```
    /// Checks if a subaccount is valid
    public func validate_subaccount(subaccount : ?T.Subaccount) : Bool {
        switch (subaccount) {
            case (?bytes) {
                bytes.size() == 32;
            };
            case (_) true;
        };
    };
```

Is this intended? The standard does not mention that it SHOULD be exactly 32 bytes, but I recall the reference implementation returns false in case the `subaccount` is not exactly 32 bytes

Thnx to @v2i0s2h2 for catching this!

**Comment by tomijaga** [comment]
Hello, have there been any instances where the token accepted transfers from an account with a subaccount that wasn't 32 bytes?

There may have been some confusion because of the catch-all syntax I used in the second switch statement. Allow me to clarify:

- The first case in the switch statement matches an option type with a Blob value (`?Blob`) and ensures that the Blob size is precisely 32 bytes.

- The second case matches any other type of `subaccount` that was not previously matched. Because the `Subaccount` is an `Option` type, the only type that can be passed into this second case is `Null`. The `Null` type is an accepted subaccount value, so the switch statement returns `true`.

You can refer to the recently added [test case](https://github.com/NatLabs/icrc1/blob/main/tests/ICRC1/Account.Test.mo#L186) that demonstrates the behaviour of the `validate_subaccount()` function.

**Comment by tomijaga** [comment]
Hey @Web3NL, just letting you know that I am closing the issue. 
Feel free to create another issue if you find any other issues with the `icrc1` implementation
